Repository Ureca-Middle-Project-Team4/4EVER0-FE, pull requests merged in 2025-06, with the labels that each got.

#4 Feat: [EVER-23] 커밋 메시지에 지라 티켓 번호 자동 붙이기
  .gitmessage.txt
  .husky/prepare-commit-msg
  package.json
Labels: ⚙ Setting

#5 Chore: [EVER-30] Storybook Update 8.6.14 -> 9.0.4
  .storybook/main.ts
  .storybook/preview.ts
  .storybook/vitest.setup.ts
  package-lock.json
  package.json
  src/components/Button/Button.stories.tsx
  src/components/Button/buttonVariants.ts
  vitest.workspace.ts
Labels: ✅ Test

#13 Feat: [EVER-90] login/logout 용 임시 페이지 업데이트, apiconfig 설정 업데이트
  package-lock.json
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/routes.tsx
  src/utils/apiconfig.ts
  src/utils/auth.ts
Labels: 📬 API, ✨ Feature

#8 Feat: [EVER-86] 디자인 시스템 초기 설정
  .storybook/preview.ts
  index.html
  package-lock.json
  package.json
  postcss.config.cjs
  public/fonts/PretendardVariable.woff2
  src/App.tsx
  src/components/Layout/Layout.tsx
  src/main.tsx
  src/pages/Test/DesignSystemTest.tsx
  src/provider/ThemeProvider.tsx
  src/routes.tsx
  src/styles/base.css
  src/styles/index.css
  src/styles/tokens.css
  src/styles/utilities.css
  tailwind.config.ts
Labels: 💻 CrossBrowsing, ✨ Feature, 🎨 Html&css

#12 Feat: [EVER-94] Naver Maps SDK, 동적 및 정적 지도 렌더링 테스트
  .husky/prepare-commit-msg
  eslint.config.mjs
  index.html
  package-lock.json
  package.json
  src/components/NaverMap/NaverMap.tsx
  src/hooks/useNaverMap.ts
  src/lib/api.ts
  src/lib/naverMap/getStaticMapUrl.ts
  src/routes.tsx
  src/types.ts/naverMap.ts
Labels: 📬 API, ✨ Feature

#14 Feat: [EVER-93] RouteObject를 이용한 기본 라우터 path 초기화
  .github/ISSUE_TEMPLATE/bug-report-form.yml
  .github/ISSUE_TEMPLATE/feature-request-form.yml
  .github/workflows/close-jira-issue.yml
  .github/workflows/create-jira-issue.yml
  .husky/prepare-commit-msg
  .prettierrc.json
  .storybook/main.ts
  .storybook/preview.ts
  .storybook/vitest.setup.ts
  .vscode/settings.json
  eslint.config.mjs
  postcss.config.cjs
  src/App.tsx
  src/components/Button/Button.stories.tsx
  src/components/Button/Button.tsx
  src/components/Button/Button.types.ts
  src/components/Button/buttonVariants.ts
  src/components/Button/index.ts
  src/components/Layout/Layout.tsx
  src/components/NaverMap/NaverMap.tsx
  src/components/ui/button.tsx
  src/components/ui/card.tsx
  src/components/ui/input.tsx
  src/components/ui/skeleton.tsx
  src/hooks/useNaverMap.ts
  src/lib/api.ts
  src/lib/naverMap/getStaticMapUrl.ts
  src/lib/utils.ts
  src/main.tsx
  src/pages/attendance/Attendance.tsx
  src/pages/chatbot/Chatbot.tsx
  src/pages/common/NotFound.tsx
  src/pages/home/Home.tsx
  src/pages/hotplace/HotPlace.tsx
  src/pages/landing/Landing.tsx
  src/pages/login/Login.tsx
  src/pages/me/MyPage.tsx
  src/pages/me/change-plans/ChangePlans.tsx
  src/pages/me/coupons/Coupons.tsx
  src/pages/me/events/Events.tsx
  src/pages/me/likes/Likes.tsx
  src/pages/mission/Mission.tsx
  src/pages/test/DesignSystemTest.tsx
  src/pages/ubti/UBTI.tsx
  src/pages/upltuple/UplTuple.tsx
  src/provider/ThemeProvider.tsx
  src/routes.tsx
  src/styles/base.css
  src/styles/index.css
  src/styles/utilities.css
  src/types/naverMap.ts
  src/utils/apiconfig.ts
  src/utils/auth.ts
  src/utils/openai.ts
  tailwind.config.ts
  tsconfig.app.json
  vite.config.ts
  vitest.workspace.ts
Labels: ⚙ Setting, ✨ Feature

#18 Feat: [EVER-112] 등록되지 않은 사용자의 경우 로그인 시도 시 회원가입 진행하는 기능 추가
  src/lib/api/apiconfig.ts
  src/pages/Signup.tsx
  src/pages/login/Login.tsx
  src/routes.tsx
  src/utils/auth.ts
Labels: 📬 API

#21 Refactor: [EVER-117] 레이아웃 컴포넌트 리팩토링
  src/components/Layout/BaseLayout.tsx
  src/components/Layout/BottomNav.tsx
  src/components/Layout/Layout.tsx
  src/components/Layout/TopNav.tsx
  src/pages/Signup.tsx
  src/routes.tsx
Labels: 🔨 Refactor

#25 Feat: [EVER-116] hot place shadcn
  package-lock.json
  package.json
  src/components/Scroll/Scrollbar.tsx
  src/components/ui/scroll-area.tsx
  src/pages/hotplace/HotPlace.tsx
Labels: ✨ Feature

#39 Feat: [EVER-131] tabs component와 스토리북 구현하기
  package-lock.json
  package.json
  src/components/Tabs/Tabs.stories.tsx
  src/components/Tabs/Tabs.tsx
  src/components/Tabs/Tabs.types.ts
  src/components/Tabs/index.ts
  src/components/ui/tabs.tsx
Labels: ✨ Feature

#32 Feat: [EVER-127] 공통 Skeleton 컴포넌트 구현
  src/components/Skeleton/Skeleton.stories.tsx
  src/components/Skeleton/Skeleton.types.ts
  src/components/Skeleton/index.ts
  src/components/ui/skeleton.tsx
Labels: ✨ Feature

#33 Feat: [EVER-124] 공통 Progress 컴포넌트 구현
  package-lock.json
  package.json
  src/components/Progress/Progress.stories.tsx
  src/components/Progress/Progress.tsx
  src/components/Progress/Progress.types.ts
  src/components/Progress/index.ts
  src/components/Progress/progressVariants.ts
  src/components/ui/progress.tsx
Labels: ✨ Feature

#38 Feat: [EVER-128] 공통 Modal 컴포넌트 만들기 및 전역 스토어 등록
  package-lock.json
  package.json
  src/App.tsx
  src/components/Modal/Modal.stories.tsx
  src/components/Modal/Modal.tsx
  src/components/Modal/Modal.types.ts
  src/components/Modal/index.ts
  src/components/Modal/modalVariants.ts
  src/hooks/useModal.ts
  src/provider/GlobalModalProvider/GlobalModalProvider.tsx
  src/stores/useModalStore.ts
  src/styles/tokens.css
Labels: ✅ Test, ✨ Feature

#42 Fix: [EVER-135] 의존성 문제 해결 및 린터 적용
  package-lock.json
  package.json
  src/components/ui/tabs.tsx
Labels: 🐞 BugFix

#35 Feat: [EVER-125] 공통 아바타, 스크롤바 component 및 storybook구현하기
  package-lock.json
  package.json
  public/images/profile.png
  src/components/Avatar/Avatar.stories.tsx
  src/components/Avatar/Avatar.tsx
  src/components/Avatar/Avatar.types.ts
  src/components/Avatar/avartarVarients.ts
  src/components/ChatBubble/ChatBubble.tsx
  src/components/Scroll/Scrollbar.tsx
  src/components/Scrollbar/Scrollbar.stories.tsx
  src/components/Scrollbar/Scrollbar.tsx
  src/components/Scrollbar/index.ts
  src/components/ui/avatar.tsx
  src/constant/iconPath.ts
Labels: ✨ Feature

#44 Feat: [EVER-132] Storybook 자동 배포를 위한 GitHub Actions CI/CD 파이프라인 구축
  .github/workflows/chromatic.yml
Labels: ✅ Test, 🌏 Deploy

#45 Feat: [EVER-136] Switch 컴포넌트 다양화 및 Storybook 스토리 추가
  package-lock.json
  package.json
  src/components/Switch/Switch.stories.tsx
  src/components/Switch/Switch.tsx
  src/components/Switch/Switch.types.ts
  src/components/Switch/index.ts
  src/components/ui/switch.tsx
Labels: ✨ Feature

#57 Fix: [EVER-160] 워크플로우 자체를 원본 레포에서만 실행
  .github/workflows/chromatic.yml
Labels: 🐞 BugFix, 🌏 Deploy

#65 Feat: [EVER-171] Banner 컴포넌트 구현
  src/components/Banner/Banner.stories.tsx
  src/components/Banner/Banner.tsx
  src/components/Banner/Banner.types.ts
  src/components/Banner/bannerVariants.ts
  src/components/Banner/index.ts
Labels: ✅ Test, ✨ Feature

#82 Feat: [EVER-173] 핫플 페이지 구현하기
  .gitattributes
  public/fonts/PretendardVariable.woff2
  src/apis/coupon/getTopCoupons.ts
  src/components/Card/TopCouponCard.stories.tsx
  src/components/Card/TopCouponCard.tsx
  src/pages/hotplace/HotPlace.tsx
Labels: ✨ Feature

#81 Feat: [EVER-173] Naver Map API를 사용한 팝업스토어 전체 및 근처 조회 PopupMap 컴포넌트 구현
  eslint.config.mjs
  src/apis/popup/getAllPopups.ts
  src/apis/popup/getNearbyPopups.ts
  src/apis/popup/getNearbyPopupsByLocation.ts
  src/apis/popup/getPopupById.ts
  src/components/Popover/popoverVartiants.ts
  src/hooks/useNaverMap.ts
  src/pages/hotplace/HotPlace.tsx
  src/pages/hotplace/PopupMap/MapControls.tsx
  src/pages/hotplace/PopupMap/MapLegend.tsx
  src/pages/hotplace/PopupMap/MapPopover.tsx
  src/pages/hotplace/PopupMap/PopupMap.tsx
  src/styles/tokens.css
  src/types/naverMap.ts
  src/types/popup.ts
  src/utils/markerClustering.ts
Labels: 📬 API, ✨ Feature

#86 Feat: [EVER-181] PopoverButton Update & tailwind 속성 수정 & SNS Share API 연동
  package-lock.json
  package.json
  src/components/Popover/FocusableButton.tsx
  src/components/Popover/Popover.stories.tsx
  src/components/Popover/Popover.tsx
  src/components/Popover/Popover.types.ts
  src/components/Popover/popoverVartiants.ts
  src/pages/share/KakaoShare.ts
  src/pages/share/SharePopover.tsx
  src/pages/share/ShareTest.tsx
  src/pages/share/apikey.ts
  src/pages/share/useFacebookShare.ts
  src/pages/share/useShare.ts
  src/pages/share/useTwitterShare.ts
  src/routes.tsx
  tailwind.config.ts
Labels: ✨ Feature, 🎨 Html&css

#85 Feat: [EVER-186] 홈페이지 디자인 변경 및 Sooner 추가
  src/components/Layout/Layout.tsx
  src/components/Layout/TopNav.tsx
  src/components/Sooner/Sonner.tsx
  src/components/ui/sonner.tsx
  src/pages/home/Home.tsx
Labels: 🎨 Html&css

#90 Refactor: [EVER-187] 불필요한 의존성 제거 및 번들 최적화 설정
  .gitignore
  package-lock.json
  package.json
  src/apis/coupon/getUserCoupons.ts
  src/pages/me/coupons/CouponTicket.tsx
  src/utils/getTicketBackground.ts
  vite.config.ts
Labels: 🥰 Accessibility

#103 Feat: [EVER-179] 타코시그널 페이지 구현하기
  package-lock.json
  package.json
  public/images/taco-berry-back.png
  public/images/taco-berry-front.png
  public/images/taco-crunch-back.png
  public/images/taco-crunch-front.png
  public/images/taco-eggy-back.png
  public/images/taco-eggy-front.png
  public/images/taco-greeny-back.png
  public/images/taco-greeny-front.png
  public/images/taco-main-back.png
  public/images/taco-main-front.png
  public/images/taco-milky-back.png
  public/images/taco-milky-front.png
  public/images/taco-pan.png
  public/images/taco-signal.png
  public/images/taco-spicy-back.png
  public/images/taco-spicy-front.png
  public/images/taco-sub-back.png
  public/images/taco-sub-front.png
  public/images/taco-sweetchoco-back.png
  public/images/taco-sweetchoco-front.png
  public/images/taco-wasab-back.png
  public/images/taco-wasab-front.png
  src/constant/imagePath.ts
  src/pages/ubti/UBTI.tsx
  src/pages/ubti/dummy.json
Labels: ✨ Feature, 🎨 Html&css

#120 Feat: [EVER-209] 로그인/로그아웃 버튼 호버 시 손가락 커서 적용 추가
  src/components/Layout/TopNav.tsx
Labels: ✨ Feature

#118 Fix: [EVER-207] 마이페이지 쿠폰 보유 수 표시 오류 수정
  src/pages/me/MyPage.tsx
Labels: 🐞 BugFix

#126 Feat: [EVER-213] 로고 및 캐릭터 변경
  public/images/moonoz-hello.png
  public/images/moonoz-logo.png
  public/images/moonoz-logo.svg
  src/constant/imagePath.ts
  src/pages/auth/Login.tsx
  src/pages/ubti/UBTI.tsx
Labels: 🎨 Html&css

#129 Feat: [EVER-197] intro 영상 logo 수정
  public/videos/intropop.MP4
  public/videos/moonointro.MP4
  src/pages/intro/Intro.tsx
Labels: ✨ Feature

#132 Feat: [EVER-217] 마이페이지 및 홈화면 기능 개선 및 사용자 데이터 반영
  src/pages/home/Home.tsx
  src/pages/me/MyPage.tsx
  src/pages/mission/Mission.tsx
Labels: ✨ Feature

#133 Feat: [EVER-169] 요금제 페이지 구현하기
  src/apis/plan/getAllPlans.ts
  src/apis/plan/getCurrentPlan.ts
  src/apis/plan/postPlan.ts
  src/components/PlanCard/PlanCard.tsx
  src/hooks/useAllPlan.ts
  src/hooks/usePlanDetail.ts
  src/pages/chatbot/ChatBubble.tsx
  src/pages/home/Home.tsx
  src/pages/me/change-plans/ChangePlans.tsx
  src/pages/plan/Plan.tsx
  src/pages/plan/PlanDetail.tsx
  src/pages/plan/PlanItem.tsx
  src/routes.tsx
  src/types/plans.ts
Labels: 📬 API, ✨ Feature, 🎨 Html&css

#138 Feat: [EVER-221] 출석 도장 반영 딜레이 수정
  src/apis/attendance/attendance.ts
  src/hooks/useAttendance.ts
  src/pages/mission/Attendance/AttendanceBanner.tsx
Labels: 📬 API, ✨ Feature, 🔨 Refactor

#137 Refactor: [EVER-208] 타코시그널 공유 기능 추가, 검사 시 오버레이 높이 줄이기 등
  src/apis/ubti/ubti.ts
  src/components/SubscriptionCard/SubscriptionCard.tsx
  src/components/ui/input.tsx
  src/hooks/useStreamingChat.ts
  src/lib/streaming/streamProcessor.ts
  src/pages/chatbot/ChatBubble.tsx
  src/pages/chatbot/ChatContainer/ChatContainer.tsx
  src/pages/chatbot/ChatHeader.tsx
  src/pages/chatbot/ChatInputArea/ChatInput.tsx
  src/pages/chatbot/UBTIOverlay.tsx
  src/pages/ubti/ActionButtons.tsx
  src/pages/ubti/LoadingOverlay.tsx
  src/pages/ubti/MatchingTypeCard.tsx
  src/pages/ubti/SharePage.tsx
  src/pages/ubti/UBTI.tsx
  src/pages/ubti/UBTITypeCard.tsx
  src/routes.tsx
  src/types/ubti.ts
Labels: 📬 API, 🥰 Accessibility, ✨ Feature, 🎨 Html&css, 🔨 Refactor

#144 Feat: [EVER-192] NAVER MAPS API를 활용한 주변 매장 조회 서비스 구현 완료
  package-lock.json
  package.json
  src/App.tsx
  src/pages/auth/Callback.tsx
  src/pages/hotplace/HotPlace.tsx
  src/pages/hotplace/StoreMap/MapControls.tsx
  src/pages/hotplace/StoreMap/MapLegend.tsx
  src/pages/hotplace/StoreMap/SelectorPopover.tsx
  src/pages/hotplace/StoreMap/StoreMap.tsx
Labels: ✨ Feature, 🎨 Html&css

#146 Feat: [EVER-227] UBTI 공유 시 미션 진행도 +1 되도록 구현
  src/pages/attendance/Attendance.tsx
  src/pages/share/SharePopover.tsx
  src/pages/ubti/ActionButtons.tsx
  src/routes.tsx
Labels: 📬 API, ✨ Feature, 🎨 Html&css

#150 Feat: [EVER-229] coupon 컴포넌트 제작
  src/components/Coupon/Coupon.stories.tsx
  src/components/Coupon/Coupon.tsx
  src/components/Coupon/Coupon.types.ts
  src/components/Coupon/couponVariants.ts
  src/components/Coupon/index.ts
  src/components/ui/coupon.tsx
Labels: ✨ Feature, 🎨 Html&css

#149 Feat: [EVER-228] 사용량 기반 API 연동 및 챗봇 페이지에 버튼 추가
  src/apis/chat/usage.ts
  src/components/BaseSwiper/BaseSwiper.tsx
  src/components/UsageAnalysisCard/UsageAnalysisCard.tsx
  src/hooks/useChatMutation.ts
  src/hooks/useStreamingChat.ts
  src/lib/streaming/index.ts
  src/lib/streaming/types.ts
  src/pages/chatbot/ChatBubble.tsx
  src/pages/chatbot/ChatContainer/ChatContainer.tsx
  src/pages/chatbot/ChatContainer/PremiumFeatureButton.tsx
  src/pages/chatbot/ChatInputArea/ChatInputArea.tsx
  src/stores/useChatStore.ts
  src/types/chat.ts
  src/types/streaming.ts
Labels: ✨ Feature, 🎨 Html&css

#148 Feat: [EVER-225] 핫플 UI 디자인 리팩토링 & 제목 크기 및 색상 통일
  package-lock.json
  package.json
  public/images/mooner-hotplace.png
  src/constant/imagePath.ts
  src/pages/auth/Signup.tsx
  src/pages/chatbot/ChatHeader.tsx
  src/pages/home/Home.tsx
  src/pages/home/Subscription.tsx
  src/pages/hotplace/HotPlace.tsx
  src/pages/hotplace/PopupMap/MapControls.tsx
  src/pages/hotplace/PopupMap/MapLegend.tsx
  src/pages/hotplace/PopupMap/MapPopover.tsx
  src/pages/hotplace/StoreMap/MapControls.tsx
  src/pages/hotplace/StoreMap/MapLegend.tsx
  src/pages/hotplace/StoreMap/SelectorPopover.tsx
  src/pages/me/MyPage.tsx
  src/pages/mission/Mission.tsx
  src/pages/upltuple/UplTuple.tsx
Labels: 🎨 Html&css, 🔨 Refactor

#154 Feat: [EVER-230] 로그아웃 확인 모달 구현
  src/App.tsx
  src/components/Layout/Layout.tsx
  src/components/Layout/TopNav.tsx
Labels: ✨ Feature

#156 Feat: [EVER-231] 쿠폰 타입 및 API 응답 처리 개선
  src/components/Coupon/Coupon.tsx
  src/pages/me/coupons/CouponTicket.tsx
  src/pages/me/coupons/Coupons.tsx
  src/types/coupon.ts
Labels: ✨ Feature

#157 Refactor: [EVER-234] 레이아웃 너비 600px로 수정
  src/components/Layout/BottomNav.tsx
  src/components/Layout/Layout.tsx
  src/components/Layout/TopNav.tsx
Labels: 🥰 Accessibility, 🔨 Refactor

#158 Feat: [EVER-222] 버튼 variant, 스토리북 수정
  src/components/Button/Button.stories.tsx
  src/components/Button/buttonVariants.ts
Labels: 🎨 Html&css, 🔨 Refactor

#163 Feat: [EVER-236] 미션 페이지 UI 수정 (각 기능 탭으로 분리, 각 탭에 배너 추가, 배너와 토스탭 스토리북 구현)
  public/images/mooner-origin.svg
  public/images/mooner-present.svg
  src/components/Banner/Banner.stories.tsx
  src/components/Banner/Banner.tsx
  src/components/Banner/bannerVariants.ts
  src/components/Tabs/FlatTabs.stories.tsx
  src/components/Tabs/FlatTabs.tsx
  src/constant/imagePath.ts
  src/pages/mission/Attendance/AttendanceBanner.tsx
  src/pages/mission/Mission.tsx
  src/pages/mission/Mission/MissionBanner.tsx
  src/pages/mission/Uplus/UplusBanner.tsx
  src/pages/mission/Uplus/UplusBenefit.module.css
  src/pages/mission/Uplus/UplusBenefitDetail.tsx
  src/pages/mission/Uplus/UplusBenefitPreview.tsx
  src/pages/mission/Uplus/UplusCalendar.tsx
Labels: ✨ Feature, 🎨 Html&css, 🔨 Refactor

#169 Feat: [EVER-242] 채팅 화면에서 Back to Top 버튼 구현 및 스크롤 훅 추가
  src/components/common/ScrollToTopButton/ScrollToTopButton.tsx
  src/hooks/useScrollToTop.ts
  src/hooks/useScrollTracker.ts
  src/pages/chatbot/ChatContainer/ChatContainer.tsx
  src/pages/chatbot/ChatMessages.tsx
  src/stores/useScrollStore.ts
Labels: 🥰 Accessibility, ✨ Feature

#178 Docs: [EVER-244] README.md 1차 초안 작성
  README.md
Labels: 📃 Docs

#176 Feat: [EVER-194] likedcoupons 조회 페이지 설계
  src/apis/coupon/getCoupons.ts
  src/apis/like/getLikeCoupons.ts
  src/pages/hotplace/HotPlace.tsx
  src/pages/me/MyPage.tsx
  src/pages/me/likes/Likes.tsx
Labels: 🎨 Html&css

#173 Feat: [EVER-236] 유플투쁠 혜택 카테고리 필터 및 미션의 각 탭 디자인 개선
  public/images/mooner-pencil.svg
  src/components/Banner/Banner.tsx
  src/components/BrandColor/BrandColors.stories.tsx
  src/components/MissionList/MissionList.tsx
  src/components/Tabs/FlatTabs.stories.tsx
  src/constant/imagePath.ts
  src/pages/mission/Attendance/AttendanceBanner.tsx
  src/pages/mission/Mission.tsx
  src/pages/mission/Uplus/CategoryFilter.tsx
  src/pages/mission/Uplus/UplusBanner.tsx
  src/pages/mission/Uplus/UplusBenefitPreview.tsx
  src/pages/mission/Uplus/UplusCalendar.tsx
  src/types/uplus.ts
  src/utils/brandColor.ts
Labels: ✨ Feature, 🎨 Html&css

#184 Refactor: [EVER-250] 챗봇 인터페이스 개선 및 Alert 시스템 도입
  src/components/Layout/Layout.tsx
  src/components/common/ScrollToTopButton/ScrollToTopButton.tsx
  src/hooks/useStreamingChat.ts
  src/pages/chatbot/ChatBubble.tsx
  src/pages/chatbot/ChatContainer/ChatContainer.tsx
  src/pages/chatbot/ChatHeader.tsx
  src/pages/chatbot/ChatInputArea/ChatInput.tsx
  src/pages/chatbot/ChatInputArea/ChatInputArea.tsx
  src/pages/chatbot/ChatInputArea/ServiceCard.tsx
  src/pages/chatbot/ChatMessages.tsx
  src/pages/chatbot/ChatSkeleton.tsx
  src/utils/alertUtils.ts
Labels: ✨ Feature, 🎨 Html&css, 🔨 Refactor

#181 Feat: [EVER-247] 타코시그널 검사 질문 UI
  src/pages/chatbot/UBTIOverlay.tsx
Labels: 🎨 Html&css

#189 Refactor: [EVER-253] Promotion banner 리팩토링
  src/components/PromotionalBanner/PromotionalBanner.tsx
Labels: 🎨 Html&css, 🔨 Refactor

#197 Feat: [EVER-257] QA 피드백 반영하여 요금제카드, 유독 가입 후 페이지 네비게이션 경로, 프로모션 배너 중 타코시그널 배너 수정
  public/images/banner-1-desktop.png
  public/images/banner-1.png
  src/components/BillSummaryCard/BillSummaryCard.tsx
  src/components/PromotionalBanner/PromotionalBanner.tsx
  src/pages/home/SubscriptionSteps/SubscriptionSteps.tsx
Labels: 🎨 Html&css, 🔨 Refactor

#200 Refactor: [EVER-259] 유저 베타테스트 QA 피드백 반영 - 0603
  src/apis/coupon/changeCouponlike.ts
  src/apis/plan/postPlan.ts
  src/components/SubscriptionCard/SubscriptionCard.tsx
  src/pages/chatbot/ChatBubble.tsx
  src/pages/chatbot/ChatContainer/ChatContainer.tsx
  src/pages/chatbot/ChatInputArea/ChatInputArea.tsx
  src/pages/chatbot/ChatbotIntroTutorial.tsx
  src/pages/home/Subscription.tsx
  src/pages/plan/Plan.tsx
  src/pages/plan/PlanDetail.tsx
  src/pages/ubti/MatchingTypeCard.tsx
  src/pages/ubti/TacoCookingAnimation.tsx
  src/pages/ubti/UBTI.tsx
  src/pages/ubti/UBTITypeCard.tsx
Labels: 💻 CrossBrowsing, 🐞 BugFix, 🔨 Refactor

#204 Design: [EVER-260] 마이페이지 프로필 및 보유 포인트, 프로그래스 바, 등급 통합 UI 수정
  src/pages/me/MyPage.tsx
Labels: 🎨 Html&css

#207 Refactor: [EVER-258] 유저 베타테스트 QA 피드백 반영 2
  package-lock.json
  package.json
  src/components/TopCouponCard/TopCouponCard.tsx
  src/pages/hotplace/HotPlace.tsx
  src/pages/mission/Mission.tsx
  tailwind.config.ts
Labels: 🎨 Html&css, 🔨 Refactor

#212 Refactor: [EVER-261] QA Feedback - 3
  src/components/Button/Button.stories.tsx
  src/components/Button/buttonVariants.ts
  src/components/NaverMap/MapLegendBox.tsx
  src/pages/hotplace/PopupMap/MapControls.tsx
  src/pages/hotplace/PopupMap/MapLegend.tsx
  src/pages/intro/Tutorial.tsx
  src/pages/intro/TutorialSlide.tsx
Labels: ✨ Feature, 🎨 Html&css, 🔨 Refactor

#213 Refactor: [EVER-261] QA Feedback -3
  src/components/SelectedProductsCard/SelectedProductsCard.stories.tsx
  src/components/SelectedProductsCard/SelectedProductsCard.tsx
  src/pages/home/SubscriptionSteps/PaymentStep.tsx
Labels: ✨ Feature, 🎨 Html&css

#217 Feat: [EVER-249] 타코시그널 검사지 & 랜딩페이지 UI 수정
  public/images/taco-secret.png
  src/constant/imagePath.ts
  src/pages/chatbot/UBTIOverlay.tsx
  src/pages/ubti/LoadingOverlay.tsx
Labels: 🎨 Html&css, 🔨 Refactor

#222 Refactor: [EVER-269] QA-Feedback-6 버튼 컴포넌트 통일
  src/components/MissionList/MissionList.tsx
Labels: 🎨 Html&css, 🔨 Refactor

#224 Refactor: [EVER-266] 인풋 자동 포커스 해제 #209
  src/pages/chatbot/ChatInputArea/ChatInput.tsx
Labels: 🥰 Accessibility

#225 Refactor: [EVER-276] QA 피드백 반영 코드 리팩토링 - 7
  public/images/banner-5-desktop.png
  public/images/banner-5.png
  src/components/PromotionalBanner/PromotionalBanner.tsx
  src/components/SelectedProductsCard/SelectedProductsCard.tsx
  src/constant/imagePath.ts
  src/pages/home/SubscriptionSteps/PaymentStep.tsx
  src/pages/home/SubscriptionSteps/SubscriptionHeader.tsx
  src/pages/home/SubscriptionSteps/SubscriptionSteps.tsx
  src/pages/mission/Uplus/UplusCalendar.tsx
Labels: ✨ Feature, 🎨 Html&css, 🔨 Refactor

#230 Feat: [EVER-263] 무너즈 사용설명서 제작(Landing Page)
  public/images/iPhone-2.png
  public/images/iPhone-3.png
  public/images/iPhone-home.png
  public/images/iPhone-mission.png
  public/images/iPhone-moonotalk.png
  public/images/iPhone.png
  src/constant/imagePath.ts
  src/pages/landing/landing.tsx
Labels: 🎨 Html&css, 🔨 Refactor

#231 Fix: [EVER-279] 요금제 변경/해지 기능 완성 및 userProfile 상태 변화 체크
  src/apis/plan/postPlan.ts
  src/pages/home/Home.tsx
  src/pages/me/MyPage.tsx
  src/pages/plan/PlanDetail.tsx
Labels: 📬 API, 🎨 Html&css

#235 핫플, 마이페이지 상단 간격 mt-4로 통일 #234: [EVER-282] 핫플, 마이페이지 상단 간격 mt-4로 통일 #234
  src/pages/hotplace/HotPlace.tsx
  src/pages/me/MyPage.tsx
Labels: 🎨 Html&css, 🔨 Refactor

#239 Refactor: [EVER-263] landing page(무너즈 설명서) UI 수정
  public/images/iPhone-home.png
  public/images/iPhone-hotplace.png
  public/images/iPhone-mypage.png
  src/constant/imagePath.ts
  src/pages/landing/landing.tsx
Labels: 🎨 Html&css, 🔨 Refactor
